### ISSUE TITLE
Support for clustering multipart quests

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-api#16]
Better condensing/presentation of multi part quests. Probably requires additional metadata, and maybe a different api return format.

**Comment by toddmedema** [comment]
See this issue for further brainstorming: https://github.com/ExpeditionRPG/expedition-quest-creator/issues/283

**Comment by toddmedema** [comment]
Duplicate of https://github.com/ExpeditionRPG/expedition-api/issues/35
