### ISSUE TITLE
Log per-user quest play events to sql

### ISSUE THREAD

**Issue by smartin015** [ExpeditionRPG/expedition-api#36]
Building block for recommendation engine... and much needed from a business analytics standpoint.

Similarly useful will be to have a `users` table that records id, email, lastLogin, loginCount. Enables us to do targeted outreach to VIP / heavy players, as well as those who haven't logged in in a long time.

**Comment by toddmedema** [comment]
Imagining something like table `user_plays`

```
{
  user_id
  quest_id
  numplayers
  start (timestamp) <- defined on creation
  end (timestamp) <- on app "end" log, assigns that timestamp to the most recent entry with the specific user_id + quest_id
  node_ids: string, comma-separated list of all IDs visited during this playthrough (views >= 1)
}
```

From that, we can calculate a LOT of stats, including:
- Most-played quests
- % of plays that finish a quest (ie `end` defined)
- Quests with very high or low finish ratios
- Average player counts (for fun: by time of day and day of week)
- Eventually: use in per-user recommendation engine (combined with their ratings). For example, if they don't finish a quest, count it (lightly) as if they didn't like it, and if they did finish it, (lightly) as if they liked it. Their actual ratings are much stronger signals, of course.

I could also see future value in transmitting an array of all of the IDs they visited while playing. That would eventually give authors insights into which choices players favor, and for now should be pretty easy to store as a massive comma-separated string.

**Comment by toddmedema** [comment]
Waiting on https://github.com/ExpeditionRPG/expedition-quest-creator/issues/23 since that'll change the data structure a bit (ie we'll want to be recording per user, quest and chapter number)
