### ISSUE TITLE
Use Sequelize timestamps for updated and created columns

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-api#39]
Add
```
createdAt: Sequelize.DATE,
updatedAt: Sequelize.DATE,
```

To each model + DB table, remove `timestamps: false` and test that it works as expected. Update any references that are hard coded into existing queries

Then, update the app to use new columns (replacing created, published and updated columns).

Finally, we can migrate & remove the existing created, published and updated columns.

**Comment by smartin015** [comment]
Backlogging :( would be nice to have consistency, but this involves a data migration and would take nonzero effort.
